[package]
name = "collatz"
version = "0.0.1"
authors = ["valkyrie_pilot <valk@randomairborne.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]